services:
    bot:
        build: .
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
            - ./config:/app/config
        networks:
            - salt-network

    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        env_file:
            - .env
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        networks:
            - salt-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-saltbot}"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    salt-network:
        driver: bridge

volumes:
    postgres_data:
