apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salt-bot-logs-pvc
  namespace: salt-bot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
