apiVersion: v1
kind: Secret
metadata:
  name: salt-bot-secrets
  namespace: salt-bot
type: Opaque
stringData:
  TOKEN: '${{ secrets.TOKEN }}'
  FEEDBACK_WEBHOOK: '${{ secrets.FEEDBACK_WEBHOOK }}'
  POSTGRES_URI: '${{ secrets.POSTGRES_URI }}'
