apiVersion: v1
kind: Secret
metadata:
  name: salt-bot-secrets
  namespace: salt-bot
type: Opaque
stringData:
  TOKEN: '${{ secrets.BOT_TOKEN }}'
  FEEDBACK_WEBHOOK: '${{ secrets.FEEDBACK_WEBHOOK }}'
  POSTGRES_USER: '${{ secrets.POSTGRES_USER }}'
  POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'
  POSTGRES_DB: '${{ secrets.POSTGRES_DB }}'
  POSTGRES_URI: 'postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5434/${{ secrets.POSTGRES_DB }}'
