bot:
    owners: ["1234567890"]
    support:
        link: "https://discord.gg/XzE9hSbsNb"
    presence:
        enabled: true
        status: idle # online, idle, dnd, invisible
        interval: 10000
        activity: # PLAYING, LISTENING, WATCHING, STREAMING
            [
                { "name": "your queries and questions!", "type": "LISTENING" },
                { "name": "<clientname> Tickets!", "type": "LISTENING" },
                { "name": "<usersize> Users!", "type": "LISTENING" },
                { "name": "version <version>", "type": "PLAYING" },
                { "name": "with <guildsize> Servers!", "type": "PLAYING" },
                { "name": "<channelsize> Channels!", "type": "WATCHING" },
            ]
    command:
        prefix: "!"
        disable_message: true
        cooldown_message: You are on `<duration>` cooldown!
        register_specific_commands:
            enabled: true
            commands: ["node"]
    log:
        command: "1234567890" # Command Log Channel ID
        server: "1234567890" # New/Left Server Log Channel ID

embed:
    color:
        default: Burple
        error: Red
        success: Green
        warning: Yellow
